### ISSUE TITLE
MessageLabels support only one label

### ISSUE THREAD

**Issue by drbrownman** [gguibon/ezcat#1]
Came across this tool as i was searching for conversation/dialog annotation tools and realized there are not many modern tools that support multi-turn text annotation (without breaking them down into per turn text annotation tasks). This tool can be really useful for many tasks such as intent classification, dialog act classification, etc.

I tried modifying the settings to add more than one MessageLabels and it appears it only uses the first message label to generate the UI. Would be great to have the support for multiple message labels.

Happy to help if you are interested in building this further together.

**Comment by gguibon** [comment]
Thank you for your feedback, glad to see you find the tool useful. 
We are aware of the limitation you highlighted. We plan to add the following:
- multilabel annotation (for instance multiple intents) for messages
- multiple labels for messages : for instance intent, emotion, etc.

I am currently working on it and the update will come soon, by the end of next week.

**Comment by gguibon** [comment]
The EZCAT 1.1.1 is up and deployed. The default annotation scheme contains emotions and intents. Feel free to adapt it to your needs.

EZCAT 1.1.1 comes with some new features:
- multilabel at the message level
- multiple label types at the message level
- new message level display (chips), customizable for each label (`listselect` or `chip`). Chips are now the default display for message level labels as it allows a faster annotation process
- fix: intermediate display on big phones. Now the labels are always visible even in intermediate to small screens
- fix: the app will automatically fix the underlaying data representation to correspond to multilabels for message labels

You can find the [release here](https://github.com/gguibon/ezcat/releases/tag/release_1.1.1)
The deployed version is updated and available at the [same url](https://gguibon.github.io/ezcat/)

**Comment by drbrownman** [comment]
Awesome. Thanks Gael. The new demo looks great. I am going to try using this in our workflow next week.

I am wondering how you envision this tool will be integrated into data annotation workflows where input data + config is passed to it by some other piece of software and when the annotator is done, output can be read by a third piece of software.
