### ISSUE TITLE
Cannot load any modified json file to be annotated

### ISSUE THREAD

**Issue by seeotter1** [gguibon/ezcat#2]
Hello, great vision on this project, thank you!

Problem: when running your default 'Start' version, everything seems to come up ok. But I took your dummy json file, modified a few values, and then tried to upload it to be the new target file. The file selection for upload seems to work ok. But once I've selected a file, I hit enter and nothing happens. The dummy file that you already have in there does not change at all. It seems to basically ignore the load process completely. I changed a few key values (like the customer number as the main key in each conversation). 

The rest of your interface seems to work fine. Can you instruct me how to load a new json conversation file to replace the default in your 'Start' view?

Thank you very much for any assistance!

**Comment by gguibon** [comment]
Hello Seeotter1,

Thank you for your interest in this app. One of the common explanation is that the JSON is not parsed correctly such as:

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/8986236/208447484-ad81e2db-1386-4d94-956a-ec8a630e7e98.png">

I invite you to check the validity of the JSON file using a JSON validator. For instance, the above warning has been triggered by putting: 
<img width="186" alt="image" src="https://user-images.githubusercontent.com/8986236/208449608-7a6e6805-77cc-4137-ad83-a5f29940dcc9.png">
While the trailing comma actually triggers a parsing error. The correct version being:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/8986236/208449512-fa9dff52-fcfc-43ec-a781-e73e548f0c5b.png">

Thanks to your feedback, I'll add more feedback in the user interface about the error triggered by the app while uploading a file.

**Comment by gguibon** [comment]
Please find the absolute minimal JSON file here: [https://github.com/gguibon/ezcat/blob/main/public/dummy_files/dummy_chats_minimal.json](https://github.com/gguibon/ezcat/blob/main/public/dummy_files/dummy_chats_minimal.json)

Please don't hesitate to tell me if it still does not solve your issue.

**Comment by seeotter1** [comment]
Ah! Thank you, your minimal json works fine. It's strange, because in my test file, I only changed a few digits of one ID number in your own example json, and it validates fine with a json validator. (see the first ID num in this screenshot, it ends in  "99" instead of your original) Anyway thank you so much for your attention to this, great system and nice interface design here for sure :)
![Screen Shot 2022-12-19 at 7 42 16 AM](https://user-images.githubusercontent.com/49382266/208465159-6ed7ecc3-13b3-4b16-8e69-510628924b60.png)

**Comment by seeotter1** [comment]
Oh ok! Now I see what I did wrong, the ID display is from the "id" field not from the overall entry key! Now it shows up as "81880299" it was loading correctly all along lol. THANK YOU :)

**Comment by gguibon** [comment]
Nice to know it solved your issue. I hope you will enjoy using the application :)
I close the issue as it seems solved.
